---
title: "Untitled"
format: html
---


```{r}

library(dplyr)
library(tidyverse)
library(readr)

#demfile <- readr::read_rds("1_15_day_2023_DEM.rds")


```


```{r}

households$HHwKidsUpTo14 <- str_sub(tamstest$H, 1, 1)
households$HHsize <- str_sub(tamstest$H, 2, 2)
households$HHRegion <- str_sub(tamstest$H, 3, 3)
households$HHIncome <- str_sub(tamstest$H, 4,4)
households$HHDwelling <- str_sub(tamstest$H, 5,5)
households$SEC <- str_sub(tamstest$H, 6, 6)
households$regionCluster <- str_sub(tamstest$H, 7, 7)


```

# And the individual variables from "value"

```{r}
members$AgeGrp <- substr(tamstest$value, 5, 5)
members$Gender <- substr(tamstest$value, 6, 6 )
members$Nationality <- substr(tamstest$value, 7, 7)
members$Region <- substr(tamstest$value, 8, 8)
members$IndHHwKidsUpTo14 <- substr(tamstest$value, 9, 9)
members$IndHHIncome <- substr(tamstest$value, 10, 10)
members$Education <- substr(tamstest$value, 11, 11)
members$Occupation <- substr(tamstest$value, 12, 12)
members$MaritalStatus <- substr(tamstest$value, 13, 13)
members$HOH <- substr(tamstest$value, 14, 14)
members$Guardian <- substr(tamstest$value, 15, 15)

```

# extract numeric weight

```{r eval=F}

tamstest$HHweight <- sub(".*W", "", tamstest$W)
```


```{r eval=F}

tamstest$weight <- sub(".*W", "", tamstest$value)
```




# Save before starting to write labels and deleting raw columns

```{r eval=F}
saveRDS(tamstest, file = "tamstest.WO_Labels_With_Raw_columns.rds")
```


# Labels for HH variables

```{r}


tamstest$HHwKidsUpTo14 <-
  factor(
    tamstest$HHwKidsUpTo14,
    levels = c(
      "1",
      "2"
    ),
    labels = c(
      "HH with Kids up to 14 - Yes",
      "HH with Kids up to 14 - No"
    )
  )



tamstest$HHsize <-
  factor(
    tamstest$HHsize,
    levels = c(
      "1",
      "2",
      "3",
      "4"
    ),
    labels = c(
      "Household Size - 1-2",
      "Household Size - 3-4",
      "Household Size - 5-6",
      "Household Size - 7+"
    )
  )



tamstest$HHRegion <-
  factor(
    tamstest$HHRegion,
    levels = c("1",
               "3",
               "3",
               "4",
               "5"),
    labels = c(
      "Central Region Cities",
      "Ad-Dammam",
      "Eastern Region - Other Cities",
      "Western Region",
      "Northern + Southern Region"
      
    )
  )



tamstest$HHIncome <-
  factor(
    tamstest$HHIncome,
    levels = c(
      "1",
      "2",
      "3",
      "4"
    ),
    labels = c(
      "Household Income - High",
      "Household Income - Medium",
      "Household Income - Low",
      "Household Income - Not Disclosed"
    )
  )



tamstest$HHDwelling <- 
  factor(tamstest$HHDwelling,
         levels = c(
           "1",
           "2",
           "3"
         ),
         labels = c(
           "Traditional house",
           "Villa",
           "Apartment"
         ))




tamstest$AgeGrp <-
  factor(
    tamstest$AgeGrp,
    levels = c(1, 2, 3, 4, 5, 6),
    labels = c(
      "Age Group 4-9",
      "Age Group 10-14",
      "Age Group 15-24",
      "Age Group 25-34",
      "Age Group 35-44",
      "Age Group 45+"
    )
  )




tamstest$Gender <-
  factor(tamstest$Gender,
    levels = c(
      "1",
      "2"
    ),
    labels = c(
      "Male",
      "Female"
    )
  )



tamstest$Nationality <-
  factor(
    tamstest$Nationality,
    levels = c(1, 2, 3),
    labels = c(
      "Nationality - Saudi",
      "Nationality - Arab Expats",
      "Nationality - Non Arab Expats"
    )
  )



tamstest$Region <-
  factor(
    tamstest$Region,
    levels = c("1",
               "4",
               "3",
               "5"),
    labels = c(
      "Central Region Cities",
      "Western Region Cities",
      "Eastern Region Cities",
      "North + South Region Cities"
      
    )
  )



tamstest$IndHHwKidsUpTo14 <-
  factor(
    tamstest$IndHHwKidsUpTo14,
    levels = c(
      "1",
      "2"
    ),
    labels = c(
      "Ind HH with Kids up to 14 - Yes",
      "Ind HH with Kids up to 14 - No"
    )
  )



tamstest$IndHHIncome <-
  factor(
    tamstest$IndHHIncome,
    levels = c(
      "1",
      "2",
      "3",
      "4"
    ),
    labels = c(
      "Ind Household Income - High",
      "Ind Household Income - Medium",
      "Ind Household Income - Low",
      "Ind Household Income - Not Disclosed"
    )
  )




tamstest$Education <-
  factor(
    tamstest$Education,
    levels = c(
      1,
      2,
      3,
      4
    ),
    labels = c(
      "Education - Up to Elementary",
      "Education - Up to Secondary/Ugraduate",
      "Education - Bachelor/Grad/PGrad",
      "Under 14yo"
    )
  )




tamstest$Occupation <-
  factor(tamstest$Occupation,
    levels = c(1, 2, 3, 4, 5, 6),
    labels = c(
      "Occupation - Employer",
      "Occupation - Employee",
      "Occupation - Not Working/Unemployed/Retired",
      "Housewife",
      "Student",
      "0-14"
    )
  )




tamstest$MaritalStatus <-
  factor(
    tamstest$MaritalStatus,
    levels = c(1, 2, 3, 4, 5),
    labels = c(
      "Marital Status - Single/Never Married",
      "Marital Status - Married",
      "Marital Status - Divorced/Separated",
      "Marital Status - Widowed",
      "Under 14yo"
    )
  )



tamstest$HOH <-
  factor(
    tamstest$HOH,
    levels = c(
      1,
      2
    ),
    labels = c(
      "Head of Household - Yes",
      "Head of Household - No"
    )
  )



tamstest$Guardian <-
  factor(tamstest$Guardian,
    levels = c(
      1,
      2
    ),
    labels = c(
      "Guardian - Yes",
      "Guardian - No"
    )
  )





```

# Save tamstest

```{r}

#demfile <- tamstest %>% select(-H, -R, -W, -value)


readr::save_rds(households, file = "HH_1_15_2325.rds")

```
